### ISSUE TITLE
Pairs

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/grammar#8]
Given the value:
```
		test=(a=b=c=d=f)
```
The parser treats this as a set of nested pairs, so to refer to the string 'f' the reference is %test>0>0>0>0>0 (or %test>a>b>c>d)

The value:
```
		a=b=c=d=e=f
```		
looks like it should be equivalent to:
```
		a=f
		b=f
		c=f
		d=f
		e=f
```
(like in Java, C, etc.)
But it isn't.

**Comment by elliottinvent** [comment]
This works:
```
a=(b=(c=(d=(e=f))))
```

So does this: 
```
a=b=c=d=e=f
```

This doesn't work in the playground:
```
a=(b=c=d=e=f)
```

I suppose the question is whether the last example works in the grammar and if the parse tree is the same for all three examples.

If so, then this could be a job for @alexdalitz in the interpreter. If the final example is difficult to handle in the interpreter we could just call this known behaviour.

**Comment by twalmsley** [comment]
The first two examples work correctly in the java interpreter and the sandbox, but the third example fails in both. It gives this stack trace:


```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value

	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1961)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeFieldName(WriterBasedJsonGenerator.java:137)
	at uk.modl.parser.printers.ModlValueJsonSerializer.serializeInternal(ModlValueJsonSerializer.java:117)
	at uk.modl.parser.printers.ModlValueJsonSerializer.serializeInternal(ModlValueJsonSerializer.java:85)
	at uk.modl.parser.printers.ModlValueJsonSerializer.serializeInternal(ModlValueJsonSerializer.java:118)
	at uk.modl.parser.printers.ModlValueJsonSerializer.serializeInternal(ModlValueJsonSerializer.java:70)
	at uk.modl.parser.printers.ModlValueJsonSerializer.serializeInternal(ModlValueJsonSerializer.java:88)
	at uk.modl.parser.printers.ModlValueJsonSerializer.serializeInternal(ModlValueJsonSerializer.java:118)
	at uk.modl.parser.printers.ModlValueJsonSerializer.serializeInternal(ModlValueJsonSerializer.java:56)
	at uk.modl.parser.printers.ModlValueJsonSerializer.serializeInternal(ModlValueJsonSerializer.java:45)
	at uk.modl.parser.printers.ModlValueJsonSerializer.serializeStructure(ModlValueJsonSerializer.java:41)
	at uk.modl.parser.printers.ModlObjectJsonSerializer.serialize(ModlObjectJsonSerializer.java:41)
	at uk.modl.parser.printers.ModlObjectJsonSerializer.serialize(ModlObjectJsonSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
	at uk.modl.parser.printers.JsonPrinter.printModl(JsonPrinter.java:59)
	at uk.modl.parser.printers.JsonPrinter.printModl(JsonPrinter.java:34)
```
This is probably one for @alexdalitz (@elliottinvent can you reassign?)

**Comment by alexdalitz** [comment]
@elliottinvent what is your expected output in this case?

**Comment by elliottinvent** [comment]
@alexdalitz 

```
a=(b=(c=(d=(e=f))))
```

and 
```
a=b=c=d=e=f
```

Should ouput the same =>

```
{
    "a": {
        "b": {
            "c": {
                "d": {
                    "e": "f"
                }
            }
        }
    }
}
```

If the example below is difficult to handle in the interpreter then we could call it expected behaviour, but ideally it would output the same as the two other examples since it's effectively the same MODL structure, just expressed in a different way:

```
a=(b=c=d=e=f)
```

=>

```
{
    "a": {
        "b": {
            "c": {
                "d": {
                    "e": "f"
                }
            }
        }
    }
}
```

**Comment by alexdalitz** [comment]
This is now working
